version: "3.9"

services:
  api:
    build:
      context: .
    container_name: phinex_blog_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-5000}:5000"
    networks:
      - phinex_network

  caddy:
    image: caddy:2
    container_name: phinex_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs/caddy:/var/log/caddy
    depends_on:
      - api
    networks:
      - phinex_network
volumes:
  postgres_data:
    name: phinex_blog_db_data

  caddy_data:
    name: phinex_api_caddy_data

  caddy_config:
    name: phinex_api_caddy_config

networks:
  phinex_network:
    name: phinex_network
    driver: bridge