package main

import (
	"fmt"
	"log"
	"os"

	_ "github.com/epsierra/phinex-blog-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/epsierra/phinex-blog-api/src/app"
	"github.com/epsierra/phinex-blog-api/src/database"
	"github.com/gofiber/swagger"
	"github.com/joho/godotenv"
)

// @title Phinex Blog API
// @version 1.0
// @description This is the API documentation for the Phinex Blog Application.

// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:5005
// @BasePath /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {

	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}
	PORT := os.Getenv("PORT")

	// Initialize database conntention
	db, err := database.NewDatabaseConnection()
	if err != nil {
		log.Fatal("Error connection to database")
	}

	// Migrate Databases

	// err = database.AutoMigrate(db)
	// if err != nil {
	// 	log.Fatal("Error migrating models", err)
	// }

	// Create a new Fiber app
	app := app.AppSetup(db)

	app.Get("/swagger-docs/*", swagger.HandlerDefault) // default

	// Start the server
	err = app.Listen(fmt.Sprintf(":%v", PORT))
	if err != nil {
		log.Fatal("Error starting server:", err)
	}
}
